---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
source("get_data.R") # reads in ledger, vendor_attributes, vendor_locations
```

```{r}
# This removes the rows that have an astronomically large positive & negative value (e.g. 1E17, -1E17)
ledger2 <- ledger %>% group_by(
  fiscal_year, fiscal_period, check_date, fund_type, fund, 
  department, division, account, expense_category, project, 
  invoice_description, vendor_name, vendor_id, payment_id, 
  payment_method, payment_status, payment_check_num) %>%
  summarise(amount = sum(amount), .groups = "drop") %>%
  filter(amount != 0)
```


```{r}
ledger2 %>% filter(fiscal_year == 2020) %>% group_by(fund_type) %>% 
  summarise(amount = sum(amount), 
            .groups = "drop") %>% arrange(-amount) %>%
  DT::datatable()
```

```{r}
ledger2 %>% filter(fiscal_year == 2020) %>% group_by(fund_type, fund) %>%
  summarise(amount = sum(amount), .groups = "drop") %>% arrange(-amount) %>%
  DT::datatable()
```

```{r}
ledger2 %>% filter(fiscal_year == 2020) %>% group_by(department) %>%
  summarise(amount = sum(amount), .groups = "drop") %>% arrange(-amount) %>%
  DT::datatable()
```

```{r}
ledger2 %>% filter(fiscal_year == 2020) %>% group_by(department, division) %>%
  summarise(amount = sum(amount), .groups = "drop") %>% arrange(-amount) %>%
  DT::datatable()
```

```{r}
ledger2 %>% filter(fiscal_year == 2020) %>%
  ggplot() + geom_histogram(aes(amount)) + scale_x_log10()
```

